<?php

return [
    'favicon.svg',
    'template/images/About/Dooodle.svg',
    'template/images/About/Piramida_1980.png',
    'template/images/About/Piramida_2000.png',
    'template/images/About/Piramida_90.png',
    'template/images/About/about_piramida.jpg',
    'template/images/Art.svg',
    'template/images/Business.svg',
    'template/images/Careers.jpg',
    'template/images/Careers_1.jpg',
    'template/images/Careers_2.jpg',
    'template/images/Careers_3.jpg',
    'template/images/Cross.svg',
    'template/images/Duration.svg',
    'template/images/Education.svg',
    'template/images/Ig.svg',
    'template/images/Image Container.png',
    'template/images/Innovation.svg',
    'template/images/Location.svg',
    'template/images/aadffinalk-logo 1.svg',
    'template/images/arrow right black.svg',
    'template/images/arrow right.svg',
    'template/images/art.png',
    'template/images/bashkia2 1.svg',
    'template/images/bg-low.jpg',
    'template/images/business.png',
    'template/images/calendar-3d-icon.svg',
    'template/images/education.png',
    'template/images/facebook.svg',
    'template/images/greeen.png',
    'template/images/green-gradient.svg',
    'template/images/innovation.png',
    'template/images/leasing/kati-0.png',
    'template/images/leasing/kati-1.png',
    'template/images/leasing/kati-3.png',
    'template/images/leasing/kati-4.png',
    'template/images/leasing/outdoor.png',
    'template/images/leasing/piramida-final.webp',
    'template/images/logo piramida.svg',
    'template/images/menu icon.svg',
    'template/images/news-arrow.svg',
    'template/images/piramida-hero-1920.jpg',
    'template/images/piramida_block.jpg',
    'template/images/piramida_block_1.jpg',
    'template/images/rent-event-spaces.jpg',
    'template/images/rent-leasing.jpg',
    'template/images/tumo-finale2 1.svg',
];
