@php $editing = isset($event); @endphp

<div class="grid gap-5 lg:grid-cols-3">
    <div><label class="block text-sm font-medium" for="status">Status</label><select id="status" name="status" required class="mt-2 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm">@foreach ($statuses as $status)<option value="{{ $status->value }}" @selected(old('status', $event->status->value ?? 'draft') === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>
    <div><label class="block text-sm font-medium" for="published_at">Publication date</label><input id="published_at" name="published_at" type="datetime-local" value="{{ old('published_at', isset($event) ? $event->published_at?->format('Y-m-d\TH:i') : '') }}" class="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm">@error('published_at')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label class="block text-sm font-medium" for="featured_media_id">Featured image</label><select id="featured_media_id" name="featured_media_id" class="mt-2 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">No image</option>@foreach ($mediaItems as $media)<option value="{{ $media->id }}" @selected((string) old('featured_media_id', $event->featured_media_id ?? '') === (string) $media->id)>{{ $media->original_name }}</option>@endforeach</select></div>
    <div><label class="block text-sm font-medium" for="starts_at">Starts at</label><input id="starts_at" name="starts_at" type="datetime-local" value="{{ old('starts_at', isset($event) ? $event->starts_at?->format('Y-m-d\TH:i') : '') }}" required class="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm">@error('starts_at')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label class="block text-sm font-medium" for="ends_at">Ends at</label><input id="ends_at" name="ends_at" type="datetime-local" value="{{ old('ends_at', isset($event) ? $event->ends_at?->format('Y-m-d\TH:i') : '') }}" required class="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm">@error('ends_at')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label class="block text-sm font-medium" for="external_url">Registration / external URL</label><input id="external_url" name="external_url" type="url" value="{{ old('external_url', $event->external_url ?? '') }}" class="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"></div>
</div>

<div class="mt-8 space-y-5">
    @foreach ($locales as $locale => $localeName)
        @php $translation = isset($event) ? $event->translations->firstWhere('locale', $locale) : null; @endphp
        <details open class="rounded-xl border border-slate-200">
            <summary class="cursor-pointer px-5 py-4 font-semibold">{{ $localeName }} <span class="text-xs font-normal uppercase text-slate-400">{{ $locale }}</span></summary>
            <div class="grid gap-5 border-t border-slate-200 p-5 lg:grid-cols-2">
                <div><label class="block text-sm font-medium">Title</label><input name="translations[{{ $locale }}][title]" value="{{ old("translations.{$locale}.title", $translation?->title) }}" required class="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm">@error("translations.{$locale}.title")<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
                <div><label class="block text-sm font-medium">Slug</label><input name="translations[{{ $locale }}][slug]" value="{{ old("translations.{$locale}.slug", $translation?->slug) }}" placeholder="Generated from title when blank" class="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm">@error("translations.{$locale}.slug")<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
                <div><label class="block text-sm font-medium">Location</label><input name="translations[{{ $locale }}][location]" value="{{ old("translations.{$locale}.location", $translation?->location) }}" class="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"></div>
                <div><label class="block text-sm font-medium">Short description</label><textarea name="translations[{{ $locale }}][short_description]" rows="3" class="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm">{{ old("translations.{$locale}.short_description", $translation?->short_description) }}</textarea></div>
                <div class="lg:col-span-2"><label class="block text-sm font-medium">Full description</label><textarea data-rich-text name="translations[{{ $locale }}][description]" rows="9" class="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2.5 font-mono text-sm">{{ app(\App\Support\RichTextSanitizer::class)->sanitize(old("translations.{$locale}.description", $translation?->description)) }}</textarea></div>
                <div><label class="block text-sm font-medium">SEO title</label><input name="translations[{{ $locale }}][seo_title]" value="{{ old("translations.{$locale}.seo_title", $translation?->seo_title) }}" class="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"></div>
                <div><label class="block text-sm font-medium">SEO description</label><textarea name="translations[{{ $locale }}][seo_description]" rows="2" class="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm">{{ old("translations.{$locale}.seo_description", $translation?->seo_description) }}</textarea></div>
            </div>
        </details>
    @endforeach
</div>
<div class="mt-8 flex justify-end gap-3 border-t border-slate-200 pt-6"><a href="{{ route('admin.events.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-medium">Cancel</a><button class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white" type="submit">{{ $editing ? 'Save event' : 'Create event' }}</button></div>
